### ISSUE TITLE
添加导入导出功能

### ISSUE THREAD

**Issue by hebeijianke** [afoim/name_html#1]
在HTML里面加一个导出按钮，打包成apk后，能把点名的记录导出来，

**Comment by afoim** [comment]
> 在HTML里面加一个导出按钮，打包成apk后，能把点名的记录导出来，

@hebeijianke 已尝试在[Release v0.4.4](https://github.com/afoim/name_html/releases/tag/v0.4.4)中支持。

---

**对于安卓APK，本项目使用的slymax/webview框架可能不支持导入导出功能**，你可以直接前往[app/src/main/assets/index.html](https://github.com/afoim/name_html/blob/main/app/src/main/assets/index.html) 获得HTML文件进行自部署解决，或者使用我的在线网站 https://name.acofork.us.kg 它托管在Cloudflare Page

---
---
如果针对于此issue还有其他问题，请在此继续回复
如果有其他问题，请发起其他issue
谢谢！

**Comment by afoim** [comment]
#2 对于安卓APK的功能缺失将会在后续修复
