### ISSUE TITLE
支持PWA

### ISSUE THREAD

**Issue by hebeijianke** [afoim/name_html#2]
在浏览器中打开导入导出按钮功能正常，打包的APK，点击导入导出按钮没反应，

**Comment by afoim** [comment]
这个是因为本项目打包APK使用的框架为 https://github.com/slymax/webview 我尝试添加了权限但是它不起作用，后续会考虑自己实现webpreview -> Android APK。你可以先使用在线网站 https://name.acofork.us.kg/

**Comment by afoim** [comment]
> 在浏览器中打开导入导出按钮功能正常，打包的APK，点击导入导出按钮没反应，

已经支持PWA，直接前往 https://name.acofork.us.kg 将其作为应用安装即可，可以直接在浏览器中作为应用安装。部分安卓浏览器不支持PWA，比如Edge，会显示顶部的搜索栏等，请使用Chrome

---

安卓请使用Chrome
![74d4770ef63d7a44cc9e1c9babd6da2d](https://github.com/user-attachments/assets/a723ee58-f7a2-4696-b95b-7f087409aa3a)


![436e170dbc4b22d8938c8f84d76ec63e](https://github.com/user-attachments/assets/526385cc-14aa-4e69-bb80-0b0c70447242)

桌面端请使用Edge、Chrome
![image](https://github.com/user-attachments/assets/8099cee0-afca-4b6b-b68f-e3953bbd2103)
